FROM debian:wheezy
MAINTAINER Kohei MATSUSHITA <ma2shita@plathome.co.jp>

ENV _BUILD_ROOT /tmp/pd-client_builder

COPY . ${_BUILD_ROOT}

RUN apt-get update && apt-get install make
WORKDIR ${_BUILD_ROOT}
RUN make setup

CMD ["rake1.9.1", "all"]
